---
# tasks file for ansible-cis-ubuntu-2204

# ------------------------------------------------------------------------------

- name: "PRE | run apt cache update"
  ansible.builtin.apt:
    force_apt_get: true
    update_cache: true
  changed_when: false
# ------------------------------------------------------------------------------
