---
# handlers file for ansible-cis-ubuntu-2204

# ------------------------------------------------------------------------------

- name: "HANDLER | 1.1.2.1 | systemd restart and enable tmp.mount"
  become: true
  ansible.builtin.systemd:
    name: tmp.mount
    daemon_reload: true
    enabled: true
    masked: false
    state: reloaded
  listen: systemd restart and enable tmp.mount
  when: ansible_virtualization_type != "docker"

- name: "HANDLER | 1.1.3.1 | systemd restart and enable var.mount"
  become: true
  ansible.builtin.systemd:
    name: var.mount
    daemon_reload: true
    enabled: true
    masked: false
    state: reloaded
  listen: systemd restart and enable var.mount
  when: ansible_virtualization_type != "docker"

- name: "HANDLER | 1.1.4.1 | systemd restart and enable var.tmp.mount"
  become: true
  ansible.builtin.systemd:
    name: var.tmp.mount
    daemon_reload: true
    enabled: true
    masked: false
    state: reloaded
  listen: systemd restart and enable var.tmp.mount
  when: ansible_virtualization_type != "docker"

- name: "HANDLER | 1.1.5.1 | systemd restart and enable var.log.mount"
  become: true
  ansible.builtin.systemd:
    name: var.log.mount
    daemon_reload: true
    enabled: true
    masked: false
    state: reloaded
  listen: systemd restart and enable var.log.mount
  when: ansible_virtualization_type != "docker"

- name: "HANDLER | 1.1.6.1 | systemd restart and enable var.log.audit.mount"
  become: true
  ansible.builtin.systemd:
    name: var.log.audit.mount
    daemon_reload: true
    enabled: true
    masked: false
    state: reloaded
  listen: systemd restart and enable var.log.audit.mount
  when: ansible_virtualization_type != "docker"

- name: "HANDLER | 1.1.7.1 | systemd restart and enable home.mount"
  become: true
  ansible.builtin.systemd:
    name: home.mount
    daemon_reload: true
    enabled: true
    masked: false
    state: reloaded
  listen: systemd restart and enable home.mount
  when: ansible_virtualization_type != "docker"
