---
- name: PREPARE
  hosts: all
  gather_facts: false
  tasks:
    - name: "PREPARE | install openssh-server for testing under docker"
      apt:
        name: "PREPARE | install openssh-server"
        state: present
        update_cache: yes
    - name: "PREPARE | install grub files for testing under docker"
      block:
        - name: "PREPARE | create folder /boot/grub"
          file:
            name: /boot/grub
            state: directory
          changed_when: false

        - name: "PREPARE | touch /boot/grub/grub.cfg"
          file:
            name: /boot/grub/grub.cfg
            state: touch
          changed_when: false

        - name: "PREPARE | touch /etc/default/grub"
          file:
            name: /etc/default/grub
            state: touch
          changed_when: false
