---
name: Ansible Molecule Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Molecule Test
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          check-latest: true

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt --break-system-packages

      - name: Test with molecule
        run: molecule test
        env:
          PY_COLOR: "1"
          ANSIBLE_FORCE_COLOR: "1"
